dontChroot: false
packagechooser_packagechooser:
    windows:
        - command: "/usr/local/bin/abellha-style-switch.sh windows"
    macos:
        - command: "/usr/local/bin/abellha-style-switch.sh macos"
