mode: required
method: legacy
labels:
    step: "Desktop Style"
items:
    - id: "windows"
      name: "Windows Style"
      description: "Windows 11 style, but not with bloat, haha."
    - id: "macos"
      name: "macOS Style"
      description: "MacOS inspired."
