name: Build Abéllha OS ISO

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y live-build debootstrap genisoimage squashfs-tools cpio wget

      - name: Patch live-build Contents path
        run: |
          # Corrige o caminho do Contents-amd64.gz para incluir a pasta /main/
          sudo sed -i 's|dists/\${LB_PARENT_DISTRIBUTION}/Contents-|dists/\${LB_PARENT_DISTRIBUTION}/main/Contents-|g' /usr/lib/live/build/lb_chroot_linux-image || true
          sudo sed -i 's|dists/\$LB_DISTRIBUTION/Contents-|dists/\$LB_DISTRIBUTION/main/Contents-|g' /usr/lib/live/build/lb_chroot_linux-image || true

      - name: Build ISO
        run: |
          sudo lb config
          sudo lb build

      - name: Upload ISO Artifact
        uses: actions/upload-artifact@v4
        with:
          name: abellha-os-iso
          path: '*.iso'
